name: Checks

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  flake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            accept-flake-config = true

      - uses: nix-community/cache-nix-action@v6
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('flake.lock', 'nix/**', 'flake.nix') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
          purge: true
          purge-prefixes: nix-${{ runner.os }}-
          purge-created: 0
          purge-last-accessed: 604800
          purge-primary-key: never

      - name: nix fmt --check
        run: nix fmt -- --check .

      - name: nix flake check
        run: nix flake check --print-build-logs --no-build
